Milestone5 full website
miftah1991/math-magicians pull request #5
Opened 2022-03-22 17:42 UTC by miftah1991

This is 5th milestone of the math magicians project, in this milestone below features has been added

- Create 3 pages: Home, CalculatorPage, and Quote.
- Create Header.jsx components that contain the Navigation.
- Install a third-party package called react-router-dom to render the pages.
- Create a style  folder that contains all React basic styling.

2022-03-22 18:20 UTC, DeliceLydia requested changes
## Hi @miftah1991, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Here are major highlights for your project:
- No linter errors
- Followed git workflow
- Implemented all pages required


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-03-22 18:20 UTC, DeliceLydia commented on src/pages/CalculatorPage.jsx
> +);
- [ ] I suggest that you add a color that makes it easier to see numbers on your calculator this is how it looks like now:
![cal](https://user-images.githubusercontent.com/44745855/159548892-4a92edaf-ca5a-4a26-bc5a-346b8d1cc1f2.png)

2022-03-23 13:06 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @miftah1991, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 13:11 UTC, merged

2022-03-23 13:11 UTC, miftah1991 commented
@Amrhub 

Thank you so much